In [ ]:
# ===============================
# DATA EXTRACTION SECTION
# Fetch data from SQL database
# ===============================

import pandas as pd

In [2]:
import pyodbc

In [3]:
from sqlalchemy import create_engine

In [4]:
engine = create_engine(
    "mssql+pyodbc://DESKTOP-CH6UADE\\SQLEXPRESS/ecommerce_project?driver=ODBC+Driver+17+for+SQL+Server"
)

In [ ]:
# First query select from orders table

query = "SELECT * FROM orders"

In [19]:
orders = pd.read_sql(query,engine)

In [ ]:
# Second query select from Customers table

query2 = "SELECT * FROM customers"

In [21]:
customers = pd.read_sql(query2,engine)

In [25]:
# ===============================
# DATA INSPECTION
# Inspecting both dataset
# ===============================

orders.head()

,Order_ID,Customer_ID,Product_ID,Order_Date,Quantity,Price,Payment_Method,Delivery_Status,Total_Amount
0,100000,1940,109,2024-02-11,2,44005,NetBanking,Delivered,88010
1,100001,7379,175,2025-07-22,2,41355,UPI,Not Delivered,82710
2,100002,658,180,2024-08-23,5,47613,Cash,Delivered,238065
3,100003,3668,145,2025-06-03,4,25531,Cash,Not Delivered,102124
4,100004,1054,189,2024-08-02,4,28894,NetBanking,Not Delivered,115576

In [26]:
customers.head()

   Customer_ID Customer_Name       City Signup_Date
0            1    Customer_1       Pune  2024-09-09
1            2    Customer_2     Jaipur  2023-01-21
2            3    Customer_3    Chennai  2023-03-05
3            4    Customer_4       Pune  2023-06-14
4            5    Customer_5  Bangalore  2023-01-27

In [27]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         50000 non-null  int64
 1   Customer_ID      50000 non-null  int64
 2   Product_ID       50000 non-null  int64
 3   Order_Date       50000 non-null  object
 4   Quantity         50000 non-null  int64
 5   Price            50000 non-null  int64
 6   Payment_Method   49500 non-null  object
 7   Delivery_Status  49700 non-null  object
 8   Total_Amount     50000 non-null  int64
dtypes: int64(6), object(3)
memory usage: 3.4+ MB

In [28]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    8000 non-null   int64
 1   Customer_Name  8000 non-null   object
 2   City           7800 non-null   object
 3   Signup_Date    8000 non-null   object
dtypes: int64(1), object(3)
memory usage: 250.1+ KB

In [34]:
# ===============================
# CHECKING MISSING VALUE
# ===============================

orders.isnull().sum()

Order_ID           0
Customer_ID        0
Product_ID         0
Order_Date         0
Quantity           0
Price              0
Payment_Method     0
Delivery_Status    0
Total_Amount       0
dtype: int64

In [36]:
customers.isnull().sum()

Customer_ID      0
Customer_Name    0
City             0
Signup_Date      0
dtype: int64

In [ ]:
# Filling Null values in order table with unknown

orders['Payment_Method'] = orders['Payment_Method'].fillna('Unknown')

In [33]:
orders['Delivery_Status'] = orders['Delivery_Status'].fillna('Unknown')

In [ ]:
# Filling Null values in customers table with unknown

customers['City'] = customers['City'].fillna('Unknown')

In [38]:
# ===============================
# CONVERTING DATE COLUMNS
# ===============================

orders['Order_Date'] = pd.to_datetime(orders['Order_Date'])

In [42]:
customers['Signup_Date'] = pd.to_datetime(customers['Signup_Date'])